DROP DATABASE farmerdata;
CREATE SCHEMA farmerdata;
USE farmerdata;

FLUSH privileges;

SHOW GLOBAL VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 'ON';
SHOW GLOBAL VARIABLES LIKE 'local_infile';

USE farmerdata;

CREATE TABLE `airlines` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `website` VARCHAR(255) DEFAULT NULL,
  `facebook` VARCHAR(255) DEFAULT NULL,
  `twitter` VARCHAR(255) DEFAULT NULL,
  `youtube` VARCHAR(255) DEFAULT NULL, 
  `othermedia` VARCHAR(255) DEFAULT NULL,
  `street` VARCHAR(255) DEFAULT NULL,
  `city` VARCHAR(255) DEFAULT NULL,
  `county` VARCHAR(255) DEFAULT NULL,
  `state`  VARCHAR(255) DEFAULT NULL,
  `zip` VARCHAR(255) DEFAULT NULL,
  `season1date` VARCHAR(255) DEFAULT NULL,
  `season1time` VARCHAR(255) DEFAULT NULL,
  `season2date` VARCHAR(255) DEFAULT NULL,
  `season2time` VARCHAR(255) DEFAULT NULL,
  `season3date` VARCHAR(255) DEFAULT NULL,
  `season3time` VARCHAR(255) DEFAULT NULL,
  `season4date` VARCHAR(255) DEFAULT NULL,
  `season4time` VARCHAR(255) DEFAULT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `location` VARCHAR(255) DEFAULT NULL ,
  `credit` VARCHAR(255) DEFAULT NULL,
  `wic` VARCHAR(255) DEFAULT NULL,
  `wiccash` VARCHAR(255) DEFAULT NULL,
  `sfmnp` VARCHAR(255) DEFAULT NULL,
  `snap`VARCHAR(255) DEFAULT NULL,
  `organic` BOOLEAN DEFAULT NULL,
  `bakedgoods` BOOLEAN DEFAULT NULL,
  `cheese` BOOLEAN DEFAULT NULL,
  `crafts` BOOLEAN DEFAULT NULL,
  `flowers` BOOLEAN DEFAULT NULL,
  `eggs` BOOLEAN DEFAULT NULL,
  `seafood` BOOLEAN DEFAULT NULL,
  `herbs` BOOLEAN DEFAULT NULL,
  `vegetables` BOOLEAN DEFAULT NULL,
  `honey` BOOLEAN DEFAULT NULL,
  `jams` BOOLEAN DEFAULT NULL,
  `maple` BOOLEAN DEFAULT NULL,
  `meat` BOOLEAN DEFAULT NULL,
  `nursery` BOOLEAN DEFAULT NULL,
  `nuts` BOOLEAN DEFAULT NULL,
  `plants` BOOLEAN DEFAULT NULL,
  `poultry` BOOLEAN DEFAULT NULL,
  `prepared` BOOLEAN DEFAULT NULL,
  `soap` BOOLEAN DEFAULT NULL,
  `trees` BOOLEAN DEFAULT NULL,
  `wine` BOOLEAN DEFAULT NULL,
  `coffee` BOOLEAN DEFAULT NULL,
  `beans` BOOLEAN DEFAULT NULL,
  `fruits` BOOLEAN DEFAULT NULL,
  `grains` BOOLEAN DEFAULT NULL,
  `juices` BOOLEAN DEFAULT NULL,
  `mushrooms` BOOLEAN DEFAULT NULL,
  `petfood` BOOLEAN DEFAULT NULL,
  `tofu` BOOLEAN DEFAULT NULL,
  `wildharvested` BOOLEAN DEFAULT NULL,
  `updateTime` VARCHAR(255) DEFAULT NULL
);

SET GLOBAL local_infile = 'ON';

LOAD DATA INFILE 'c:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\airlines.dat' INTO TABLE airlines
FIELDS TERMINATED BY ',' ENCLOSED BY '\"'
LINES TERMINATED BY '\n' (id, name, alt_name, iata, icao, callsign, country, @var3)
SET active = (@var3 = 'Y');
SHOW WARNINGS;
SELECT * FROM airlines;
